# Generated by Django 5.1.2 on 2024-11-01 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_category_event_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='bookings',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='event',
            name='capacity',
            field=models.PositiveIntegerField(default=100),
        ),
    ]
